### ISSUE TITLE
Help with dot

### ISSUE THREAD

**Issue by Dagdelo** [auerswal/ssocr#11]
I've been trying to get the dot from those images:
![test1](https://user-images.githubusercontent.com/10082704/80253881-81b74a00-8650-11ea-8e5d-4d0813a03530.png)
![test3](https://user-images.githubusercontent.com/10082704/80253886-82e87700-8650-11ea-83de-cf12c39e701b.png)
![test4](https://user-images.githubusercontent.com/10082704/80253900-87ad2b00-8650-11ea-8644-65961a444ac3.png)
`root@42fdff91d67f:/home/imgs# ssocr -d -1 test1.png`
`345_`
`root@42fdff91d67f:/home/imgs# ssocr -d -1 -l blue test3.png`
`330`
![test-4-debug](https://user-images.githubusercontent.com/10082704/80272940-46df0180-86a4-11ea-97ca-9841908c71aa.png)
`root@42fdff91d67f:/home/imgs# ssocr -d -1 test4.png`
`2208`
`root@42fdff91d67f:/home/imgs# ssocr -d -1 shear 13 test4.png`
`2208`
`root@42fdff91d67f:/home/imgs# ssocr -d -1 shear 22 test4.png`
`22_`
`root@42fdff91d67f:/home/imgs# ssocr -d -1 shear 18 test4.png `
`2208`

I've tried to use shear flag to get the dot, but with no success. Like in #10 .

**Comment by auerswal** [comment]
Hello Henrique,

thanks for your question.  This provides me with an opportunity to show how to use `ssocr` with different input images. :-)

You have three quite different images, thus it is quite possible that you need three different sets of options.  I have downloaded the images and saved them with a name giving the number shown, i.e., `34.5.png`, `33.0.png`, and `22.08.png`.

1. `34.5.png`:

This image contains a degree Celsius (℃) unit designator that `ssocr` cannot recognize.  Thus I remove it with the `crop` command.  This results in a problem, because after the `crop` command, `ssocr` re-adjusts the threshold to the resulting image, but the original threshold value was a much better fit.  Thus I add the `make_mono` command before `crop` to keep the original thresholding.  Then there is the quite common *dot problem* that can be solved with `shear`.  In my testing, `shear` values of 8 and 9 work:

```
$ ssocr -d-1 make_mono crop 0 0 137 87 shear 8 34.5.png 
34.5
$ ssocr -d-1 make_mono crop 0 0 137 87 shear 9 34.5.png 
34.5
```

(Adding the option `--verbose` (`-v`) shows the two threshold adjustments because of `crop`.)

2. `33.8.png`:

As you already discovered, using the blue color for `--luminance` calculation helps here. The image is quite large, thus it needs a large `shear` value.  Additionally, the digits are quite tall, thus after reducing their lean with `shear`, the value 3 is recognized as a one.  This can be remedied by specifying a higher value for the `--one-ratio` (short option `-r`).  In my testing, `shear` values between 76 and 87 combined with a `--one-ratio` of 4 work:

```
$ ssocr -d-1 -lblue -r4 shear 76 33.0.png 
33.0
$ ssocr -d-1 -lblue -r4 shear 87 33.0.png 
33.0
```

(Adding the `--debug-output` (`-P`) option shows the height/width ratio and that this results in (erroneously) detecting a one for the first two digits.)

3. `22.08.png`:

This is an instance of just the *dot problem* that can be solved with shear values between 7 and 12:

```
$ ssocr -d-1 shear 7 22.08.png 
22.08
$ ssocr -d-1 shear 12 22.08.png 
22.08
```

In general, using the options `--debug-image`, `--verbose`, and `--debug-output` (in this order) combined with trial and error often helps to find `ssocr` options and commands to recognize a given image.  For the first image I needed both `--debug-image` and `--verbose`, while `--debug-image` sufficed for the other two.  But then I know how the digit one is detected and thus directly saw the problem with the second image .  To have this reported by `ssocr` requires the `--debug-output` option.

Thanks,
Erik

**Comment by Dagdelo** [comment]
Thx a lot for the explanations and guidelines!
