### ISSUE TITLE
Hints on integrating ssocr with c++

### ISSUE THREAD

**Issue by panwauu** [auerswal/ssocr#18]
Do you have any hints for me on how I can integrate ssocr directly in a C++ script without hacking it over the cli. Currently I save the image, call ssocr over the cli and then read the result. This is obviously not the best solution.
I dont have a lot of experience so I am happy for help.

**Comment by auerswal** [comment]
Perhaps calling an external `ssocr` binary is not that bad. You could consider providing the image data on *standard input* instead of saving it to a file (then `ssocr` would save it to a file automatically, but in a quite simple way without any optimization), so this would just free from you having to implement this temporary file handling in your code.

I have never intended for `ssocr` to be used as a library, and I have no intention to change that. Thus I cannot describe how to integrate it into C or C++ nicely.

**Comment by panwauu** [comment]
Thanks for your comment
